# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "373309145f93b36a43af3e7b8ec4c732"
name = "popup-app"
handle = "popup-app-14"
application_url = "https://controlling-consistency-rr-expansys.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "faizanss-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://controlling-consistency-rr-expansys.trycloudflare.com/auth/callback",
  "https://controlling-consistency-rr-expansys.trycloudflare.com/auth/shopify/callback",
  "https://controlling-consistency-rr-expansys.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
